M48
; DRILL file KiCad 10.0.6 date 2026-10-05T23:50:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-05T23:50:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X115.0Y-45.5
X115.0Y-154.5
X174.0Y-45.5
X174.0Y-154.5
M30
